src/Apps/WebApp/Controllers/GadoController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class GadoController : Controller
    {
        public IActionResult Compra()
        {
            return View();
        }
        public IActionResult Consulta()
        {
            return View();
        }
    }
}

src/Apps/WebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Apps/WebApp/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/Apps/WebApp/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/Apps/WebApp/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/Apps/WebApp/Pages/Index.cshtml
@page
@model IndexModel

@{
    Layout = "_Layout";
    ViewBag.Title = "Teste Marfrig";
    ViewData["BreadCrumb"] = "Home / ";
    ViewData["BreadCrumbFinal"] = "Index";
}

<div id="readme" class="Box-body readme blob js-code-block-container p-5 p-xl-6 gist-border-0">
    <article class="markdown-body entry-content container-lg" itemprop="text">
        <h1>
            Teste Marfrig - Fábio Muniz
        </h1>
        <p>
            Este é um modelo de solução para a criação de uma API da Web ASP.NET Core seguindo os princípios da Arquitetura Limpa.
        </p>
        <h2>
            Tecnologias
        </h2>
        <ul>
            <li>.NET 5.0.x</li>
            <li>ASP .NET 5.0.x</li>
            <li>Entity Framework Core 5.0.x</li>
            <li>MediatR</li>
            <li>Mapster</li>
            <li>FluentValidation</li>
            <li>Elasticsearch, Serilog, Kibana</li>
        </ul>

        <h3>
            Configuracao de Banco de Dados
        </h3>
        <p>
            O modelo é configurado para usar um banco de dados na memória por padrão. Isso garante que todos os usuários serão capazes de executar a
            solução sem a necessidade de configurar uma infraestrutura adicional (por exemplo, SQL Server).
        </p>
        <p>Se você quiser usar o SQL Server, você precisará atualizar <strong>WebApi/appsettings.json</strong> conforme abaixo:</p>
        <div class="highlight highlight-source-json position-relative">
            <pre>  <span class="pl-s"><span class="pl-pds">"</span>UseInMemoryDatabase<span class="pl-pds">"</span></span>: <span class="pl-c1">false</span>,</pre><div class="zeroclipboard-container position-absolute right-0 top-0">
            </div>
        </div>
        <p>Verifique se o <strong>DefaultConnection</strong> string de conexão dentro do <strong>appsettings.json</strong> aponta para uma instância válida do SQL Server.</p>
        <p>Ao executar o aplicativo, o banco de dados será criado automaticamente (se necessário) e as migrações mais recentes serão aplicadas.</p>

        <h2>Overview</h2>
        <h3>Domain</h3>
        <p>Aqui contém todas as entidades, enums, exceções, interfaces, tipos e lógicas específicas para a camada de domínio.</p>
        <h3>Application</h3>
        <p>
            Esta camada contém toda a lógica do aplicativo. Depende da camada de domínio, mas não depende de
            nenhuma outra camada ou projeto. Esta camada define interfaces que são implementadas por camadas externas.
            Por exemplo, se o aplicativo precisar acessar um serviço de notificação, uma nova interface seria adicionada ao aplicativo
            e uma implementação seria criada dentro da infraestrutura.
        </p>
        <h3>Infrastructure</h3>
        <p>
            Esta camada contém classes para acessar recursos externos, como sistemas de arquivos,
            serviços da web, smtp e assim por diante. Essas classes devem ser baseadas em interfaces definidas na camada de aplicativo.
        </p>
        <h3>WebApi</h3>
        <p>
            Esta camada é uma web API  baseado em ASP.NET 5.0.x. Esta camada depende das camadas de aplicativo e infraestrutura, no entanto,
            a dependência da infraestrutura serve apenas para oferecer suporte à injeção de dependência. Portanto, apenas <em> Startup.cs </em> deve fazer referência a Infraestrutura.
        </p>
        <h3>WebApp</h3>
        <p>
            Esta camada é uma web App  baseado em ASP.NET 5.0.x. Esta camada depende somente da classe client gerada pelo nSwag.
        </p>
        <h3>Logs</h3>
        <p>Login no Elasticsearch usando Serilog e visualização de registros em Kibana.</p>
    </article>
</div>

src/Apps/WebApp/Pages/Shared/_Layout.cshtml
<!doctype html>
<html class="sidebar-light sidebar-left-big-icons">
<head>

    <!-- Basic -->
    <title>@ViewData["Title"] - Titan</title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta name="keywords" content="BancoPan" />
    <meta name="description" content="Titan - Cockpit">
    <meta name="author" content="NtitSolutions|Tegra">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <!-- Vendor CSS-->
    <link rel="stylesheet" href="~/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/vendor/font-awesome/css/font-awesome.css" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="~/vendor/pnotify/pnotify.custom.css" />
    @RenderSection("CssSpecificVendor", required: false)

    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/css/theme.css" />

    <!-- Skin CSS -->
    <link rel="stylesheet" href="~/css/skins/default.css" />

    <!-- Head Libs -->
    <script src="~/vendor/modernizr/modernizr.js"></script>

</head>
<body>
    <section class="body">
        <!-- start: header -->
        <header class="header">
            <div class="logo-container">
                <a href="#" class="logo">
                    <img src="~/images/Logo-BG-Marfrig.png" style="height: 75px;" />
                </a>
                <div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
                    <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
                </div>
            </div>

            <!-- start: search & user box -->
            <div class="header-right">

                <span class="separator"></span>

                <div id="userbox" class="userbox">
                    <a href="#" data-toggle="dropdown">

                        <div class="profile-info" data-lock-name="Administrador" data-lock-email="admin@admin.com">
                            <h2 class="name">Fábio de Souza Muniz</h2>

                            <span class="role">Senior Developer/Architect</span>
                        </div>

                        <i class="fa custom-caret"></i>
                    </a>

                    <div class="dropdown-menu">
                        <ul class="list-unstyled mb-2">
                            <li>
                                &nbsp;
                                &nbsp;
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a role="menuitem" tabindex="-1" href="#"><i class="fa fa-paper-plane"></i> Release 1.0.0</a>
                            </li>
                            <li>
                                <a role="menuitem" tabindex="-1" href="#"><i class="fa fa-power-off"></i> Sair</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- end: search & user box -->
        </header>
        <!-- end: header -->

        <div class="inner-wrapper">
            <!-- start: sidebar -->
            <aside id="sidebar-left" class="sidebar-left">

                <div class="sidebar-header">
                    <div class="sidebar-title">
                        Navegação
                    </div>
                    <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
                        <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
                    </div>
                </div>

                <div class="nano">
                    <div class="nano-content">
                        <nav id="menu" class="nav-main" role="navigation">

                            <ul class="nav nav-main">
                                <li class="nav-parent">
                                    <a class="nav-link" href="@Url.Action("Compra","Gado")">
                                        <i class="fa fa-usd" aria-hidden="true"></i>
                                        <span>Compra</span>
                                    </a>
                                </li>
                                <li class="nav-parent">
                                    <a class="nav-link" href="@Url.Action("Consulta","Gado")">
                                        <i class="fa fa-search" aria-hidden="true"></i>
                                        <span>Consulta</span>
                                    </a>
                                </li>
                            </ul>
                        </nav>


                    </div>

                    <script>
                        // Maintain Scroll Position
                        if (typeof localStorage !== 'undefined') {
                            if (localStorage.getItem('sidebar-left-position') !== null) {
                                var initialPosition = localStorage.getItem('sidebar-left-position'),
                                    sidebarLeft = document.querySelector('#sidebar-left .nano-content');

                                sidebarLeft.scrollTop = initialPosition;
                            }
                        }
                    </script>


                </div>

            </aside>
            <section role="main" class="content-body">
                <header class="page-header">
                    <h2>Bem Vindo ao Teste Marfrig</h2>

                    <div class="right-wrapper text-right">
                        <ol class="breadcrumbs">
                            <li>
                                <a href="@Url.Action("Index", "Home")">
                                    <i class="fa fa-home"></i>
                                </a>
                            </li>
                            <li><span>@ViewBag.BreadCrumb</span><b><span>&nbsp;@ViewBag.BreadCrumbFinal&nbsp;&nbsp;&nbsp;&nbsp;</span></b></li>
                        </ol>
                    </div>
                </header>

                <!-- start: page -->
                @RenderBody()
                <!-- end: page -->
            </section>
        </div>

    </section>

    <!-- Vendor -->
    <script src="~/vendor/jquery/jquery.js"></script>
    <script src="~/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/vendor/popper/umd/popper.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/vendor/common/common.js"></script>
    <script src="~/vendor/nanoscroller/nanoscroller.js"></script>

    <!-- Specific Page Vendor -->
    <script src="~/vendor/pnotify/pnotify.custom.js"></script>
    @RenderSection("ScriptsSpecificVendor", required: false)

    <!-- Theme Base, Components and Settings -->
    <script src="~/js/theme.js"></script>

    <!-- Theme Initialization Files -->
    <script src="~/js/theme.init.js"></script>
    <script src="~/vendor/vue/vue.js"></script>
    <script src="~/vendor/axios/axios.min.js"></script>
    @* <script src="~/js/main.js"></script>*@

    <!-- Examples -->
    @RenderSection("Scripts", required: false)


</body>
</html>

src/Apps/WebApp/Views/Gado/Compra.cshtml
@{
    ViewData["Title"] = "Compra";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Compra</h1>

src/Apps/WebApp/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
    ViewBag.Title = "Teste Marfrig";
    ViewData["BreadCrumb"] = "Home / ";
    ViewData["BreadCrumbFinal"] = "Index";
}

<div id="readme" class="Box-body readme blob js-code-block-container p-5 p-xl-6 gist-border-0">
    <article class="markdown-body entry-content container-lg" itemprop="text">
        <h1>
            Teste Marfrig - Fábio Muniz
        </h1>
        <p>
            Este é um modelo de solução para a criação de uma API da Web ASP.NET Core seguindo os princípios da Arquitetura Limpa.
        </p>
        <h2>
            Tecnologias
        </h2>
        <ul>
            <li>.NET 5.0.x</li>
            <li>ASP .NET 5.0.x</li>
            <li>Entity Framework Core 5.0.x</li>
            <li>MediatR</li>
            <li>Mapster</li>
            <li>FluentValidation</li>
            <li>Elasticsearch, Serilog, Kibana</li>
        </ul>

        <h3>
            Configuracao de Banco de Dados
        </h3>
        <p>
            O modelo é configurado para usar um banco de dados na memória por padrão. Isso garante que todos os usuários serão capazes de executar a
            solução sem a necessidade de configurar uma infraestrutura adicional (por exemplo, SQL Server).
        </p>
        <p>Se você quiser usar o SQL Server, você precisará atualizar <strong>WebApi/appsettings.json</strong> conforme abaixo:</p>
        <div class="highlight highlight-source-json position-relative">
            <pre>  <span class="pl-s"><span class="pl-pds">"</span>UseInMemoryDatabase<span class="pl-pds">"</span></span>: <span class="pl-c1">false</span>,</pre><div class="zeroclipboard-container position-absolute right-0 top-0">
            </div>
        </div>
        <p>Verifique se o <strong>DefaultConnection</strong> string de conexão dentro do <strong>appsettings.json</strong> aponta para uma instância válida do SQL Server.</p>
        <p>Ao executar o aplicativo, o banco de dados será criado automaticamente (se necessário) e as migrações mais recentes serão aplicadas.</p>

        <h2>Overview</h2>
        <h3>Domain</h3>
        <p>Aqui contém todas as entidades, enums, exceções, interfaces, tipos e lógicas específicas para a camada de domínio.</p>
        <h3>Application</h3>
        <p>
            Esta camada contém toda a lógica do aplicativo. Depende da camada de domínio, mas não depende de
            nenhuma outra camada ou projeto. Esta camada define interfaces que são implementadas por camadas externas.
            Por exemplo, se o aplicativo precisar acessar um serviço de notificação, uma nova interface seria adicionada ao aplicativo
            e uma implementação seria criada dentro da infraestrutura.
        </p>
        <h3>Infrastructure</h3>
        <p>
            Esta camada contém classes para acessar recursos externos, como sistemas de arquivos,
            serviços da web, smtp e assim por diante. Essas classes devem ser baseadas em interfaces definidas na camada de aplicativo.
        </p>
        <h3>WebApi</h3>
        <p>
            Esta camada é uma web API  baseado em ASP.NET 5.0.x. Esta camada depende das camadas de aplicativo e infraestrutura, no entanto,
            a dependência da infraestrutura serve apenas para oferecer suporte à injeção de dependência. Portanto, apenas <em> Startup.cs </em> deve fazer referência a Infraestrutura.
        </p>
        <h3>WebApp</h3>
        <p>
            Esta camada é uma web App  baseado em ASP.NET 5.0.x. Esta camada depende somente da classe client gerada pelo nSwag.
        </p>
        <h3>Logs</h3>
        <p>Login no Elasticsearch usando Serilog e visualização de registros em Kibana.</p>
    </article>
</div>